sudo:required
services:
    - docker
    
before_install:
    - docker build -t rajdipg/docker-react -f Dockerfile.dev .
    
script:
    - docker run rajdipg/docker-react npm run test -- --coverage

